# wrangler.toml

name = "trbikes"
main = ".open-next/worker.js"
compatibility_date = "2025-10-21"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true
